### ISSUE TITLE
The Guardian shows information for The Observer?

### ISSUE THREAD

**Issue by Rohaq** [drmikecrowe/mbfcext#7]
From this post:
https://www.facebook.com/groups/YourPoliticalSay/permalink/4065950963445643/

Screenshot with mouseover:
![image](https://user-images.githubusercontent.com/246865/82659063-f5348300-9c1f-11ea-8293-3ad1e4f6747c.png)

Obviously a bit of a concern if the extension is showing the information for the wrong sites.

**Comment by JoshC8C7** [comment]
The Observer is the sunday edition of the Guardian. They're published on the same site and so the extension is technically referring to the correct site albeit by possibly the wrong name

**Comment by grahamperrin** [comment]
> The Observer is the sunday edition of the Guardian. 

Thanks. I have been an occasional reader of The Guardian for years, never knew that. 

If the check showed 'The Guardian' for a page from The Observer, it might be less surprising (and educational).

**Comment by JoshC8C7** [comment]
It should just be a case of adding an alias for guardian.com -> observer.com - but yes I agree it's a little confusing that observer be the canonical name when its widely known as the guardian.

**Comment by drmikecrowe** [comment]
@JoshC8C7 -- observer.com isn't the TLD for the guardian/observer.  I can't find one.
@Rohaq / @grahamperrin  -- I believe the extension should not be substituting The Observer for The Guarding.  IMO, this is fixed.  Any disagreement?

**Comment by JoshC8C7** [comment]
> @JoshC8C7 -- observer.com isn't the TLD for the guardian/observer. I can't find one.

Yes my bad I meant the reverse. observer (i.e. the guardians Sunday paper) -> theguardian.com/observer. And then the guardian is just theguardian.com. However Observer articles are indistinct from Guardian ones by URL, and so not sure there's an easy way to distinguish Guardian from Observer articles when not coming from the Observers page on the guardian website (so i.e. via any external link). Really the only fix needed is for observer to point to guardian rather than guardian pointing to observer as the example above indicates

**Comment by drmikecrowe** [comment]
This should be fixed.  Cleaning up issues...

**Comment by grahamperrin** [comment]
Tested with https://www.theguardian.com/uk/2007/apr/04/britishidentity.features11

Thanks
